var BaseUrl = '../assets/images/';
const Images = {
  dummySplash: require(BaseUrl + 'dummySplash.png'),
  appLogo: require(BaseUrl + 'appLogo.png'),
  google: require(BaseUrl + 'google.png'),
  downArrow: require(BaseUrl + 'arrowDown.png'),
  apple: require(BaseUrl + 'apple.png'),
  email: require(BaseUrl + 'email.png'),
  facebook: require(BaseUrl + 'facebook.png'),
  chat: require(BaseUrl + 'chat.png'),
  inbox: require(BaseUrl + 'inbox.png'),
  fav: require(BaseUrl + 'heart.png'),
  lokal: require(BaseUrl + 'lokal.png'),
  reward: require(BaseUrl + 'rewards.png'),
  test: require(BaseUrl + 'test.jpg'),
  test1: require(BaseUrl + 'test1.jpg'),
  test2: require(BaseUrl + 'test2.jpg'),
  // new icons
  address: require(BaseUrl + 'address.png'),
  gps: require(BaseUrl + 'gps.png'),
  search: require(BaseUrl + 'search.png'),
  bed: require(BaseUrl + 'bed.png'),
  measuring: require(BaseUrl + 'measuring.png'),
  bath: require(BaseUrl + 'bath.png'),
  send: require(BaseUrl + 'send.png'),
  hoa: require(BaseUrl + 'hoa.png'),
  star: require(BaseUrl + 'star.png'),
  // Slides
  slide1: require(BaseUrl + 'slide1.png'),
  slide2: require(BaseUrl + 'slide2.jpg'),
  slide3: require(BaseUrl + 'slide3.jpg'),
  slide4: require(BaseUrl + 'slide4.jpg'),
  slide5: require(BaseUrl + 'slide5.jpg'),
  like: require(BaseUrl + 'like.png'),
  dislike: require(BaseUrl + 'dislike.png'),
  // 19 Apr
  phone: require(BaseUrl + 'phone.png'),
  setting: require(BaseUrl + 'setting.png'),
  savedSearch: require(BaseUrl + 'savedSearch.png'),
  contactAgent: require(BaseUrl + 'contactAgent.png'),
  makeOffer: require(BaseUrl + 'makeOffer.png'),
  favroites: require(BaseUrl + 'favroites.png'),
  recycleBin: require(BaseUrl + 'recycleBin.png'),
  call: require(BaseUrl + 'call.png'),
  chatProp: require(BaseUrl + 'chatProp.png'),
  area: require(BaseUrl + 'area.png'),
  profile: require(BaseUrl + 'profile.png'),
  // 20 Apr
  bigCahouna: require(BaseUrl + 'bigCahouna.png'),
  fastGun: require(BaseUrl + 'fastGun.png'),
  grommet: require(BaseUrl + 'grommet.png'),
  longBoarder: require(BaseUrl + 'longBoarder.png'),
  agentInsta: require(BaseUrl + 'agentInsta.png'),
  agentPhone: require(BaseUrl + 'agentPhone.png'),
  agentTel: require(BaseUrl + 'agentTel.png'),
  agentVideo: require(BaseUrl + 'agentVideo.png'),
  meter: require(BaseUrl + 'meter.png'),
  // 24 Apr
  imageView: require(BaseUrl + 'imageView.png'),
  detail: require(BaseUrl + 'detail.png'),
  features: require(BaseUrl + 'features.png'),
  nearBy: require(BaseUrl + 'nearBy.png'),
  walkScrore: require(BaseUrl + 'walkScroe.png'),
  contactUs: require(BaseUrl + 'contactUs.png'),
  reviews: require(BaseUrl + 'reviews.png'),
  bookTour: require(BaseUrl + 'bookTour.png'),
  close: require(BaseUrl + 'close.png'),
  signOut: require(BaseUrl + 'signOut.png'),
  plus: require(BaseUrl + 'plus.png'),
};
export default Images;
